In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from mlxtend.frequent_patterns import apriori , association_rules

In [3]:
raw_data = pd.read_excel('./data/MarketBasketOptimization.xlsx',header = None)
#openpyxl

In [4]:
dataset = []
for i in range(0 , len(raw_data)):  ###ลูปตั้งแต่แถวแรกยั้นแถวสุดท้าย
    tmp = []
    for j in range(0 , len(raw_data.loc[i])) :
        if raw_data.loc[i,j] is not np.nan :
            tmp.append(raw_data.loc[i,j])
    dataset.append(tmp)

In [5]:
dataset[3]

['turkey', 'avocado']

In [6]:
from mlxtend.preprocessing import TransactionEncoder
TE = TransactionEncoder()
tmp_dataset = TE.fit_transform(dataset)

In [7]:
tmp_dataset ###True ถูกซื้อ False ไม่ถูกซื้อ

array([[False,  True,  True, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]], shape=(7501, 120))

In [8]:
df = pd.DataFrame(tmp_dataset , columns = TE.columns_)
df.head(2)

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
itemset = apriori(df.drop('mineral water',axis=1), min_support=0.01, use_colnames=True )
itemset

      support                       itemsets
0    0.020397                      (almonds)
1    0.033329                      (avocado)
2    0.010799               (barbecue sauce)
3    0.014265                    (black tea)
4    0.011465                   (body spray)
..        ...                            ...
206  0.020931          (spaghetti, tomatoes)
207  0.016531            (spaghetti, turkey)
208  0.014131  (spaghetti, whole wheat rice)
209  0.010532   (spaghetti, chocolate, eggs)
210  0.010932   (spaghetti, milk, chocolate)

[211 rows x 2 columns]

In [10]:
rule = association_rules( itemset , metric='confidence', min_threshold=0.25 )
rule

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,1.0,0.013128,1.224818,0.499424,0.120941,0.183552,0.245256
1,(burgers),(french fries),0.087188,0.170911,0.021997,0.252294,1.476173,1.0,0.007096,1.108844,0.353384,0.093168,0.098160,0.190499
2,(chicken),(spaghetti),0.059992,0.174110,0.017198,0.286667,1.646468,1.0,0.006752,1.157790,0.417698,0.079287,0.136285,0.192721
3,(cooking oil),(chocolate),0.051060,0.163845,0.013598,0.266319,1.625432,1.0,0.005232,1.139671,0.405483,0.067550,0.122553,0.174656
4,(salmon),(chocolate),0.042528,0.163845,0.010665,0.250784,1.530617,1.0,0.003697,1.116040,0.362067,0.054496,0.103975,0.157939
5,(shrimp),(chocolate),0.071457,0.163845,0.017998,0.251866,1.537221,1.0,0.006290,1.117654,0.376370,0.082822,0.105269,0.180856
6,(cooking oil),(spaghetti),0.051060,0.174110,0.015865,0.310705,1.784531,1.0,0.006975,1.198166,0.463284,0.075796,0.165391,0.200911
7,(herb & pepper),(eggs),0.049460,0.179709,0.012532,0.253369,1.409883,1.0,0.003643,1.098656,0.305849,0.057846,0.089797,0.161551
8,(turkey),(eggs),0.062525,0.179709,0.019464,0.311301,1.732245,1.0,0.008228,1.191072,0.450907,0.087373,0.160420,0.209805
9,(frozen vegetables),(spaghetti),0.095321,0.174110,0.027863,0.292308,1.678867,1.0,0.011267,1.167018,0.446965,0.115342,0.143115,0.226169
10,(grated cheese),(spaghetti),0.052393,0.174110,0.016531,0.315522,1.812196,1.0,0.007409,1.206597,0.472963,0.078730,0.171223,0.205234
11,(herb & pepper),(ground beef),0.049460,0.098254,0.015998,0.323450,3.291994,1.0,0.011138,1.332860,0.732460,0.121457,0.249734,0.243136
12,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,1.0,0.022088,1.373997,0.624943,0.168096,0.272197,0.312015
13,(herb & pepper),(spaghetti),0.049460,0.174110,0.016264,0.328841,1.888695,1.0,0.007653,1.230543,0.495018,0.078457,0.187350,0.211128
14,(honey),(spaghetti),0.047460,0.174110,0.011865,0.250000,1.435873,1.0,0.003602,1.101187,0.318684,0.056580,0.091889,0.159074
15,(olive oil),(milk),0.065858,0.129583,0.017064,0.259109,1.999567,1.0,0.008530,1.174826,0.535135,0.095665,0.148810,0.195398
16,(soup),(milk),0.050527,0.129583,0.015198,0.300792,2.321232,1.0,0.008651,1.244861,0.599484,0.092158,0.196697,0.209038
17,(milk),(spaghetti),0.129583,0.174110,0.035462,0.273663,1.571779,1.0,0.012900,1.137061,0.417935,0.132207,0.120540,0.238669
18,(olive oil),(spaghetti),0.065858,0.174110,0.022930,0.348178,1.999758,1.0,0.011464,1.267048,0.535186,0.105651,0.210764,0.239939
19,(pancakes),(spaghetti),0.095054,0.174110,0.025197,0.265077,1.522468,1.0,0.008647,1.123778,0.379218,0.103279,0.110144,0.204897
20,(red wine),(spaghetti),0.028130,0.174110,0.010265,0.364929,2.095966,1.0,0.005368,1.300468,0.538028,0.053472,0.231046,0.211944
21,(salmon),(spaghetti),0.042528,0.174110,0.013465,0.316614,1.818472,1.0,0.006060,1.208527,0.470079,0.066273,0.172546,0.196975
22,(shrimp),(spaghetti),0.071457,0.174110,0.021197,0.296642,1.703760,1.0,0.008756,1.174209,0.444850,0.094474,0.148363,0.209194
23,(soup),(spaghetti),0.050527,0.174110,0.014265,0.282322,1.621513,1.0,0.005468,1.150780,0.403689,0.067807,0.131024,0.182126
24,(tomatoes),(spaghetti),0.068391,0.174110,0.020931,0.306043,1.757755,1.0,0.009023,1.190117,0.462740,0.094465,0.159746,0.213129
25,(turkey),(spaghetti),0.062525,0.174110,0.016531,0.264392,1.518535,1.0,0.005645,1.122731,0.364245,0.075106,0.109315,0.179669
26,"(spaghetti, chocolate)",(eggs),0.039195,0.179709,0.010532,0.268707,1.495234,1.0,0.003488,1.121700,0.344719,0.050544,0.108496,0.163656
27,"(spaghetti, eggs)",(chocolate),0.036528,0.163845,0.010532,0.288321,1.759721,1.0,0.004547,1.174905,0.448096,0.055478,0.148868,0.176301
28,"(chocolate, eggs)",(spaghetti),0.033196,0.174110,0.010532,0.317269,1.822232,1.0,0.004752,1.209686,0.466715,0.053523,0.173339,0.188880
29,"(spaghetti, milk)",(chocolate),0.035462,0.163845,0.010932,0.308271,1.881480,1.0,0.005122,1.208790,0.485728,0.058033,0.172726,0.187496
30,"(spaghetti, chocolate)",(milk),0.039195,0.129583,0.010932,0.278912,2.152382,1.0,0.005853,1.207088,0.557239,0.069257,0.171560,0.181637
31,"(milk, chocolate)",(spaghetti),0.032129,0.174110,0.010932,0.340249,1.954217,1.0,0.005338,1.251821,0.504495,0.055973,0.201163,0.201518